services:
  postgres:
    #База данных PostgreSQL
    image: postgres:15
    container_name: de_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    
    #--------------------------------------------------------------------
    #Графический интерфейс pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: de_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: always

    #--------------------------------------------------------------------
  # оркестратор
  # 1. Инициализация базы данных Airflow (создает служебные таблицы в Postgres)
  airflow-init:
    build:
      context: .
      dockerfile: MyDockerfile.dev
    container_name: de_airflow_init
    restart: always
    #user: "0:0"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@de_postgres:5432/${POSTGRES_DB}
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key"
      _AIRFLOW_DB_UPGRADE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    command: version
    depends_on:
      postgres:
        condition: service_healthy

  # 2. Веб-интерфейс Airflow (Порт 8082)
  airflow-webserver:
    build:
      context: .
      dockerfile: MyDockerfile.dev
    container_name: de_airflow_webserver
    restart: always
    ports:
      - "8082:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@de_postgres:5432/${POSTGRES_DB}
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key"
    command: webserver
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./parsers:/opt/airflow/parsers
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  # 3. планировщик запуска парсера
  airflow-scheduler:
    build:
      context: .
      dockerfile: MyDockerfile.dev
    container_name: de_airflow_scheduler
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONUNBUFFERED: "1"  # Рекомендуется: логи парсера будут видны в реальном времени
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@de_postgres:5432/${POSTGRES_DB}
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key"
      #
      DB_HOST: de_postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}  # имя БД для данных парсера не совпадает с БД для Airflow
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      #      
      SSH_HOST: ${SSH_HOST}
      SSH_PORT: ${SSH_PORT}
      SSH_USER: ${SSH_USER}
      SSH_PASSWORD: ${SSH_PASSWORD}
      SOCKS_PORT: ${SOCKS_PORT}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./parsers:/opt/airflow/parsers
    command: scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully


volumes:
  pgdata: {}
  pgadmin_data: {} 
